### ISSUE TITLE
Starting message disappears

### ISSUE THREAD

**Issue by Philipp-M** [glepnir/galaxyline.nvim#160] opened 2021-05-08 19:05 UTC
This issue may be a little bit nitpicky...

The Starting message like this:
```
~                    NVIM v0.5.0-dev
~
~      Nvim is open source and freely distributable
~                https://neovim.io/#chat
~
~     type  :help nvim<Enter>       if you are new!
~     type  :checkhealth<Enter>     to optimize Nvim
~     type  :q<Enter>               to exit
~     type  :help<Enter>            for help
~
~             Help poor children in Uganda!
~     type  :help iccf<Enter>       for information
```

disappears shortly after galaxyline is initilized (quickly flashes).

**Comment by gbaranski** [comment] 2021-05-09 09:44
duplicate of #107

**Closed** 2021-05-09 09:56 UTC
